[project]
name = "discord-ext-ui"
version = "3.1.9"
description = "An Declarative UI Kit for discord.py"
authors = [
    { name = "sizumita", email = "github@smdr.io" }
]
dependencies = [
    "aiohttp>=3.9.3",
]
readme = "README.rst"
requires-python = ">=3.8.2"
license = { text = "MIT" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ruff>=0.3.2",
    "discord.py>=2.3.2",
    "hatch>=1.9.3",
]

[tool.rye.scripts]
check = { cmd = "ruff check ." }
format = { cmd = "ruff format ." }

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/discord/ext/ui"]
#pattern = "__version__ = \"(?P<version>[^\"]+)\""

[tool.hatch.version]
path = "discord/ext/ui/__init__.py"

[tool.hatch.build.targets.sdist]
exclude = [
    ".github",
    "docs",
    ".idea",
    "samples",
    "tests",
]

[tool.ruff]
line-length = 160

[tool.ruff.lint]
extend-select = ["E501"]
